name: .NET Core

on:
  pull_request:
    branches:
      - master # CI (pr validation)
  push:
    branches:
      - master # CI (ci package)
    tags:
      - v\\d+\\.\\d+ # CD (release package)

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/e-wipond/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build Gen -c Release 
    - run: dotnet test Gen -c Release
    - run: dotnet pack Gen/GenCli -c Release
      if: github.event_name == 'push' && startswith(github.ref, 'refs/heads')
    - run: dotnet nuget push Gen/GenCli/nupkg/*.nupkg -k ${{secrets.NUGET_ORG_API_KEY}} -s https://api.nuget.org/v3/index.json
      if: github.event_name == 'push' && startswith(github.ref, 'refs/tags')

